# Site settings
title: Lucy Nyambura
email: nyamburalucy678@gmail.com
description: >-
  Network Engineer | Cloud Solutions | DevOps & Automation Enthusiast
linkedin_username: lucy-nyambura-5704a1232
github_username: lucianakenya
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.25.1"
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages
  - _projects

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author info
author:
  name: "Lucy Nyambura"
  avatar: "/assets/images/my_photo.jpeg"
  bio: "I show up. I listen. I solve."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lucy-portfolio-ebon.vercel.app/"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lucy-nyambura-5704a1232/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lucianakenya/"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lucianakenya"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lucy-portfolio-ebon.vercel.app/"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lucy-nyambura-5704a1232/"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
